version: '3.7'

services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - '5100:5100'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: stress-build-stage
      dockerfile: ../../Dockerfile
    container_name: server
    ports:
      - '${PORT}:3001'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    volumes:
      - ${POSTGRES_VOLUMEN_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
